### ISSUE TITLE
Unexpected behavior with "or"

### ISSUE THREAD

**Issue by Nightblade** [queicherius/refined-text-search#7] opened 2022-01-20 01:23 UTC
```js
const haystack = "cat dog";  // no duck here!

const needles_a = tokenize("cat dog duck");
console.debug("match_a: ", match(needles_a, haystack));
// false, as expected

const needles_b = tokenize("cat or dog duck");
console.debug("match_b: ", match(needles_b, haystack));
// true, **unexpected**
```

Maybe add support for explicit "and" to make the search pattern unambiguous?

**Comment by Nightblade** [comment] 2022-01-21 05:48
https://runkit.com/nightblade/my-bug

**Comment by queicherius** [comment] 2022-01-21 06:31
This is expected behaviour, since the evaluation works based on operator precedence (`and` gets evaluated before `or`).

Your second example can also be written like this:

```
cat OR (dog AND duck)
```

and evaluates like this:

```
true OR true AND false =
true OR (true AND false) =
true OR (false) =
true
```

What you would want would be a way to write `(cat OR dog) AND duck`, which is not currently supported by this module. If you would like to take a shot I'd be happy to merge a PR as long as the performance is similar to what it currently is (I use it to search through 100k+ items so it has to be zippy).

**Comment by Nightblade** [comment] 2022-01-21 08:15
Ah ok, thank you for clarifying.  :)

**Comment by Nightblade** [comment] 2022-01-22 02:00
`duck cat OR dog duck` works! 

Thanks for the offer, but I'm certainly not a good enough JavaScript coder to make a PR.

**Comment by queicherius** [comment] 2022-01-22 06:27
Nice! I'll close this since you found a way to make it work 😄

**Closed by queicherius** 2022-01-22 06:27 UTC
